INSERT INTO products (sku, name, category, description, price_paise, tags) VALUES
                                                                               ('GRO-001','Basmati Rice 5kg','grocery','Long grain aged basmati rice.',62000,'{vegetarian,staple}'),
                                                                               ('GRO-002','Whole Wheat Atta 5kg','grocery','Stone ground whole wheat flour.',27000,'{vegetarian,staple}'),
                                                                               ('GRO-003','Sunflower Oil 1L','grocery','Refined sunflower cooking oil.',16500,'{vegetarian,staple}'),
                                                                               ('GRO-004','Toor Dal 1kg','grocery','Split pigeon peas.',15500,'{vegetarian,staple}'),
                                                                               ('GRO-005','Paneer 200g','grocery','Fresh cottage cheese, great for grilling.',9000,'{vegetarian,bbq}'),
                                                                               ('GRO-006','Chicken Breast 1kg','grocery','Boneless skinless chicken breast.',28000,'{non-veg,bbq}'),
                                                                               ('GRO-007','Chicken Sausages 500g','grocery','Smoked chicken sausages.',32000,'{non-veg,bbq}'),
                                                                               ('GRO-008','Burger Buns 6 pack','grocery','Soft sesame burger buns.',6000,'{vegetarian,bbq}'),
                                                                               ('GRO-009','Onions 1kg','grocery','Fresh red onions.',4500,'{vegetarian}'),
                                                                               ('GRO-010','Tomatoes 1kg','grocery','Fresh ripe tomatoes.',5000,'{vegetarian}'),
                                                                               ('GRO-011','Capsicum 500g','grocery','Green capsicum, good for skewers.',4000,'{vegetarian,bbq}'),
                                                                               ('GRO-012','Sweet Corn 4 pack','grocery','Fresh corn on the cob.',6000,'{vegetarian,bbq}'),
                                                                               ('GRO-013','Butter 500g','grocery','Salted table butter.',27500,'{vegetarian}'),
                                                                               ('GRO-014','Tomato Ketchup 900g','grocery','Classic tomato ketchup.',15000,'{vegetarian,bbq}'),
                                                                               ('GRO-015','BBQ Sauce 350g','grocery','Smoky barbecue sauce.',21000,'{vegetarian,bbq}'),
                                                                               ('GRO-016','Eggs 12 pack','grocery','Farm fresh eggs.',9000,'{non-veg}'),
                                                                               ('SNK-001','Classic Salted Chips 150g','snacks','Crispy potato chips, lightly salted.',5000,'{vegetarian,party}'),
                                                                               ('SNK-002','Masala Chips 150g','snacks','Potato chips with Indian spice mix.',5000,'{vegetarian,party}'),
                                                                               ('SNK-003','Butter Popcorn 100g','snacks','Microwave butter popcorn.',6000,'{vegetarian,movie}'),
                                                                               ('SNK-004','Nachos 200g','snacks','Crunchy corn tortilla chips.',9000,'{vegetarian,movie,party}'),
                                                                               ('SNK-005','Salsa Dip 300g','snacks','Medium spicy tomato salsa.',12000,'{vegetarian,movie}'),
                                                                               ('SNK-006','Salted Peanuts 400g','snacks','Roasted salted peanuts.',11000,'{vegetarian}'),
                                                                               ('SNK-007','Chocolate Cookies 300g','snacks','Choco chip cookies.',9500,'{vegetarian}'),
                                                                               ('SNK-008','Namkeen Mix 400g','snacks','Traditional savoury snack mix.',10000,'{vegetarian}'),
                                                                               ('SNK-009','Dark Chocolate 100g','snacks','70 percent cocoa dark chocolate.',15000,'{vegetarian}'),
                                                                               ('SNK-010','Cheese Puffs 100g','snacks','Crunchy cheese flavoured puffs.',4000,'{vegetarian,party}'),
                                                                               ('SNK-011','Roasted Makhana 100g','snacks','Lightly salted fox nuts.',12000,'{vegetarian}'),
                                                                               ('SNK-012','Trail Mix 250g','snacks','Nuts, seeds and raisins.',20000,'{vegetarian}'),
                                                                               ('BEV-001','Cola 2L','beverages','Carbonated cola soft drink.',9500,'{soft-drink,party}'),
                                                                               ('BEV-002','Lemon Soda 2L','beverages','Carbonated lemon soft drink.',9000,'{soft-drink,party}'),
                                                                               ('BEV-003','Orange Soft Drink 2L','beverages','Carbonated orange soft drink.',9000,'{soft-drink,party}'),
                                                                               ('BEV-004','Bottled Water 1L 6 pack','beverages','Packaged drinking water.',12000,'{water}'),
                                                                               ('BEV-005','Mango Juice 1L','beverages','Mango fruit drink.',11000,'{juice}'),
                                                                               ('BEV-006','Iced Tea 1L','beverages','Lemon iced tea.',10000,'{juice}'),
                                                                               ('BEV-007','Sparkling Water 750ml','beverages','Plain sparkling water.',6500,'{water}'),
                                                                               ('BEV-008','Cola Cans 6 pack','beverages','Cola in 330ml cans.',24000,'{soft-drink,party}'),
                                                                               ('BEV-009','Ginger Ale 1L','beverages','Ginger flavoured soda.',9500,'{soft-drink}'),
                                                                               ('BEV-010','Coconut Water 1L','beverages','Natural coconut water.',12000,'{juice}'),
                                                                               ('BEV-011','Instant Coffee 100g','beverages','Instant coffee granules.',32000,'{hot}'),
                                                                               ('BEV-012','Black Tea 500g','beverages','Assam black tea leaves.',22000,'{hot}'),
                                                                               ('PTY-001','Paper Plates 50 pack','party','Sturdy 9 inch paper plates.',18000,'{party,bbq}'),
                                                                               ('PTY-002','Paper Cups 50 pack','party','200ml paper cups.',12000,'{party,bbq}'),
                                                                               ('PTY-003','Napkins 100 pack','party','Soft paper napkins.',8000,'{party,bbq}'),
                                                                               ('PTY-004','Balloons 50 pack','party','Assorted colour latex balloons.',15000,'{party,birthday}'),
                                                                               ('PTY-005','Birthday Candles 24 pack','party','Colourful birthday candles.',6000,'{birthday}'),
                                                                               ('PTY-006','Party Hats 10 pack','party','Cone party hats.',9000,'{party,birthday}'),
                                                                               ('PTY-007','Disposable Cutlery 50 set','party','Spoon, fork and knife sets.',14000,'{party,bbq}'),
                                                                               ('PTY-008','Happy Birthday Banner','party','Reusable letter banner.',12000,'{birthday}'),
                                                                               ('PTY-009','Charcoal 3kg','party','Natural lump charcoal for grilling.',25000,'{bbq}'),
                                                                               ('PTY-010','Return Gift Bags 10 pack','party','Printed gift bags for kids.',20000,'{birthday}'),
                                                                               ('HOM-001','Dish Soap 500ml','home','Lemon dishwashing liquid.',12000,'{cleaning}'),
                                                                               ('HOM-002','Kitchen Towel 2 rolls','home','Absorbent paper towels.',9000,'{cleaning,bbq}'),
                                                                               ('HOM-003','Aluminium Foil 72m','home','Kitchen foil roll.',25000,'{bbq}'),
                                                                               ('HOM-004','Trash Bags 30 pack','home','Medium garbage bags.',14000,'{cleaning,party}'),
                                                                               ('HOM-005','Bamboo Skewers 100 pack','home','Wooden skewers for grilling.',6000,'{bbq}'),
                                                                               ('HOM-006','Storage Box 5L','home','Airtight plastic container.',35000,'{storage}'),
                                                                               ('HOM-007','LED Bulb 9W 2 pack','home','Warm white LED bulbs.',22000,'{lighting}'),
                                                                               ('HOM-008','Extension Board 4 socket','home','Surge protected power strip.',55000,'{electrical}'),
                                                                               ('HOM-009','Picnic Mat','home','Waterproof foldable mat.',45000,'{outdoor,bbq}'),
                                                                               ('HOM-010','Insulated Cooler Bag','home','Keeps food cold for hours.',65000,'{outdoor,bbq}');

INSERT INTO stock (sku, on_hand) SELECT sku, 50 FROM products;

-- a few low-stock items (2 to 5 units) and a few sold-out items, to test substitution
UPDATE stock SET on_hand = 3 WHERE sku = 'GRO-006';
UPDATE stock SET on_hand = 2 WHERE sku = 'SNK-009';
UPDATE stock SET on_hand = 4 WHERE sku = 'BEV-005';
UPDATE stock SET on_hand = 5 WHERE sku = 'PTY-004';
UPDATE stock SET on_hand = 0 WHERE sku IN ('GRO-005','BEV-003','SNK-004');