spring.application.name=commerce-core

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/minisparky}
spring.datasource.username=${DB_USER:minisparky}
spring.datasource.password=${DB_PASSWORD:minisparky}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always